version: '3.4'

services:
  app1:
    container_name: app1
    build:
      context: .
    ports:
    - 8081:8080

  app2:
    container_name: app2
    build:
      context: .
    ports:
      - 8082:8080

  app3:
    container_name: app3
    build:
      context: .
    ports:
      - 8083:8080

  db:
    container_name: db
    image: postgres:9
    ports:
    - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  lb:
    container_name: lb
    build:
      context: ./nginx
    ports:
      - 8080:8080

  fe:
    container_name: fe
    image: ang
    ports:
      - 4200:4200