version: '3.4'

services:
  app1:
    container_name: app1
    build:
      context: .
    ports:
    - 8080:8080

  db:
    container_name: db
    image: postgres:10
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

#  lb:
#    container_name: lb
#    build:
#      context: ./nginx
#    ports:
#      - 8080:8080