spring:
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect